name: nequo
description: Quotes app.
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  sqflite: ^2.0.2
  path: ^1.7.0
  share: ^2.0.4
  google_fonts: ^2.2.0
  http: ^0.13.4
  shared_preferences: ^2.0.12
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3

  flutter_localizations:
    sdk: flutter
  internet_connection_checker: ^0.0.1+3
  package_info_plus: ^1.4.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.17

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.local
    
    - lang/en.json
    - lang/pt.json
